detectors:
  IrresponsibleModule:
    enabled: false

  TooManyStatements:
    exclude:
      - properties

  UncommunicativeVariableName:
    exclude:
      - properties

  FeatureEnvy:
    exclude:
      - Stashify::Directory::Local#write

  ControlParameter:
    exclude:
      - Stashify::Directory#initialize
