detectors:
  TooManyStatements:
    exclude:
      - properties

  UncommunicativeVariableName:
    exclude:
      - properties

  FeatureEnvy:
    exclude:
      - Stashify::Directory#write_file
      - Stashify::Directory::Local#write_file
      - Stashify::Directory#delete_directory

  ControlParameter:
    exclude:
      - Stashify::Directory#initialize

  NilCheck:
    exclude:
      - Stashify::File#exists?
