detectors:
  IrresponsibleModule:
    enabled: false

  TooManyStatements:
    exclude:
      - properties

  UncommunicativeVariableName:
    exclude:
      - properties

  FeatureEnvy:
    exclude:
      - Stashify::Directory::Local#write_file
      - Stashify::Directory#delete_directory

  ControlParameter:
    exclude:
      - Stashify::Directory#initialize
